version: '3'
services:
  express-container:
    image: wiwa1978/blog-mean-sampleapp:v1.0
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/src/app
    depends_on:
     - mongo-container
    deploy:
        placement:
            constraints: [node.role == worker]
  mongo-container:
    image: mongo
    deploy:
        placement:
            constraints: [node.role == worker]
